---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cloud-solutions-images/concourse-helm-gcp
    tag: v0.2.0

inputs:
- name: hash-anomaly-ap-fms-source

outputs:
- name: hash-anomaly-ap-fms-version

run:
  path: bash
  args:
  - -exc
  - |
    mkdir -p hash-anomaly-ap-fms-version
    cd hash-anomaly-ap-fms-source && git rev-parse --short HEAD > ../hash-anomaly-ap-fms-version/version
    git tag -l --points-at HEAD > ../hash-anomaly-ap-fms-version/tags
    
